name: Docs
on:
  push:
    branches:
      - v5
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install tox
        run: python -m pip install tox
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc
      - name: Run sphinx
        run: tox -e docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          publish_branch: gh-pages
          force_orphan: true
