name: Lint
on:
  push:
    branches:
      - v5

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install tox
        run: python -m pip install tox
      - name: Run flake
        run: tox -e lint
